# -*- coding: utf-8 -*-
"""exercicio-04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1myF4FMr5Dm7B5j_jeDqDdy2dkT9hq1Ld
"""

#Haversine Formula
import math
from math import radians, cos, sin, asin, sqrt

lat1=float(input('Insira o valor da Latitude do ponto 1: '))
lon1=float(input('Insira o valor da Longitude do ponto 1: '))
lat2=float(input('Insira o valor da Latitude do ponto 2: '))
lon2=float(input('Insira o valor da Longitude do ponto 2: '))

def haversine(lon1, lat1, lon2, lat2,d):

    """
    Calculo de distância entre dois pontos geográficos
    """
    
    # conversão de decimal para radianos 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # Raio da Terra en kilometros
    return c * r
    d = c * r
    print('A distância entre os pontos 1 e 2 é:', d, 'km')

