# -*- coding: utf-8 -*-
"""exercicio-01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/197zMPHbo0Mbw8q9qjUC1wCJT4B2pB5q2
"""

type(1)
#int

type(5+3)
#int

type(5/2)
#float

type(2.5)
#float

type(False)
#bool

type(True)
#bool