# -*- coding: utf-8 -*-
"""exercicio-03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpcuCJNJR-2Sdo6QWY2h4Vvloib3JwEe
"""

band_green=float(input('Insira o valor correpondente a banda espectral na faixa do verde: '))
band_nir=float(input('Insira o valor correpondente a banda espectral na faixa do infravermelho: '))
band_red=float(input('Insira o valor correpondente a banda espectral na faixa do vermelho: '))
ndvi = (band_nir - band_red)/(band_nir + band_red)
ndwi = (band_green-band_nir)/(band_green+band_nir)
print('O valor de NDVI é', ndvi)
print('O valor de NDWI é', ndwi)